@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package Model as ModelPackage <<Rectangle>>{
Class "<<interface>>\nReadOnlyAddressBook" as ReadOnlyAddressBook
Class "<<interface>>\nReadOnlyUserPrefs" as ReadOnlyUserPrefs
Class "<<interface>>\nReadOnlyPropertyBook" as ReadOnlyPropertyBook
Class "<<interface>>\nModel" as Model

Class AddressBook
Class PropertyBook
Class ModelManager
Class UserPrefs

Class UniqueContactList
Class UniquePropertyList

Class Contact
Class Property
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Model

AddressBook .up.|> ReadOnlyAddressBook
PropertyBook .up.|> ReadOnlyPropertyBook
UserPrefs .up.|> ReadOnlyUserPrefs

Model .right.> ReadOnlyUserPrefs
Model .left.> ReadOnlyAddressBook
Model .left.> ReadOnlyPropertyBook

ModelManager .up.|> Model
ModelManager -left-> "1" AddressBook
ModelManager -> "1" PropertyBook
ModelManager -right-> "1" UserPrefs

PropertyBook *--> "1" UniquePropertyList
AddressBook *--> "1" UniqueContactList

UniqueContactList --> "all ~*" Contact
UniquePropertyList --> "~* all" Property

ModelManager --> "~* filtered" Contact
ModelManager --> "filtered ~*" Property
@enduml
