@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor STORAGE_COLOR
skinparam classBackgroundColor STORAGE_COLOR

package Storage as StoragePackage {

package "UserPrefs Storage" #F4F6F6{
Class "<<interface>>\nUserPrefsStorage" as UserPrefsStorage
Class JsonUserPrefsStorage
}

Class "<<interface>>\nStorage" as Storage
Class StorageManager

package "PropertyBook Storage" #F4F6F6{
Class "<<interface>>\nPropertyBookStorage" as PropertyBookStorage
Class JsonPropertyBookStorage
Class JsonSerializablePropertyBook
Class JsonAdaptedProperty
}

package "AddressBook Storage" #F4F6F6{
Class "<<interface>>\nAddressBookStorage" as AddressBookStorage
Class JsonAddressBookStorage
Class JsonSerializableAddressBook
Class JsonAdaptedContact
Class JsonAdaptedTag
}

}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Storage

StorageManager .up.|> Storage
StorageManager --> "1" UserPrefsStorage
StorageManager --> "1" PropertyBookStorage
StorageManager --> "1" AddressBookStorage

Storage --|> UserPrefsStorage
Storage --|> PropertyBookStorage
Storage --|> AddressBookStorage

JsonUserPrefsStorage .up.|> UserPrefsStorage

JsonPropertyBookStorage .up.|> PropertyBookStorage
JsonPropertyBookStorage ..> JsonSerializablePropertyBook
JsonSerializablePropertyBook --> "*" JsonAdaptedProperty

JsonAddressBookStorage .up.|> AddressBookStorage
JsonAddressBookStorage ..> JsonSerializableAddressBook
JsonSerializableAddressBook --> "*" JsonAdaptedContact
JsonAdaptedContact --> "*" JsonAdaptedTag

@enduml
